#!/bin/ksh

rm -f calc.x

echo "compilando"
gfortran -ffree-line-length-none calc.f90 -o calc.x
echo "compilado"
sleep 3

if [ -s calc.x ] 
then
   echo "executando"
   time ./calc.x
   echo "executado"

   
else
   echo "deu ruim"
fi

exit

