\rm -f roms*.nc
\rm -f scrip*.nc
\rm -f atp*
\rm -f coawstM*
\rm -f Errfile01-*
\rm -f swan*
\rm -f core*
\rm -f PRINT01*
\rm -f rsl.out.000*
\rm -f wlen.mat*
\rm -f wind.mat*
\rm -f wdir.mat*
\rm -f vel.mat*
\rm -f ubot.mat*
\rm -f tmbot.mat*
\rm -f setup.mat*
\rm -f rtp.mat*
\rm -f rtp.mat*
\rm -f qb.mat*
\rm -f hsig.mat*
\rm -f fric.mat*
\rm -f dissip.mat*
\rm -f depth.mat*
\rm -f wrfout_d01_*
\rm -f rsl.out.0*
\rm -f namelist.output
\rm -f rsl.error.0*
\rm -f wrfinput_d01
\rm -f wrfbdy_d01
\rm -f wrflowinp_d01
\rm -f VEGPARM.TBL
\rm -f URBPARM.TBL
\rm -f SOILPARM.TBL
\rm -f rws1_total.out
\rm -f RRTM_DATA_DBL
\rm -f RRTM_DATA
\rm -f namelist.input
\rm -f LANDUSE.TBL
\rm -f GENPARM.TBL
\rm -f assign.txt
\rm -f rws1.err
\rm -f rws1.out
\rm -f ocean_rst.nc
\rm -f ocean_joe_tc_coarse_his.nc
\rm -f ocean_dia.nc
\rm -f ocean_avg.nc
\rm -f *init2.hot*
\rm -f xp.mat
\rm -f yp.mat
\rm -f swaninit*
\rm -f coawstM_SW12
\rm -f swa12_grd.nc
\rm -f swa12cfs_exp.in
\rm -f ocn2atm_weights*
\rm -f atm2ocn_weight*
\rm -f swa12cfs_rst_20060101.nc
\rm -f roms_bry_swa12.nc
\rm -f ocean_ATLSW12.in
\rm -f coupling_ATLSW12.in
\rm -f RRTMG* 
\rm -f coawstM
\rm -f SWA12_ocean_*.nc
\rm -f fort.*
